const FETCH_SIMPANAN_REQUEST = 'FETCH_SIMPANAN_REQUEST';
const FETCH_SIMPANAN_SUCCESS = 'FETCH_SIMPANAN_SUCCESS';
const FETCH_SIMPANAN_FAILURE = 'FETCH_SIMPANAN_FAILURE';
export {
  FETCH_SIMPANAN_REQUEST,
  FETCH_SIMPANAN_SUCCESS,
  FETCH_SIMPANAN_FAILURE,
};
